In [2]:
import numpy as np

# `np.tile` vs. `np.repeat`

In [3]:
np.tile([1, 2, 3], reps=2)

array([1, 2, 3, 1, 2, 3])

In [4]:
np.repeat([1, 2, 3], 2)

array([1, 1, 2, 2, 3, 3])

### multidimensional

In [119]:
np.tile(np.repeat([1, 2, 3, 4], 2), 3)

array([1, 1, 2, 2, 3, 3, 4, 4, 1, 1, 2, 2, 3, 3, 4, 4, 1, 1, 2, 2, 3, 3,
       4, 4])

In [122]:
d = {'b': 12}
dict({'a': 2}, **d)

{'a': 2, 'b': 12}

In [102]:
a = np.arange(4).reshape(2, -1)
np.tile(a, (2, 3))

array([[0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3]])

In [118]:
a = np.arange(4).reshape(2, -1)
np.repeat(a, (2, 5), axis=0)

array([[0, 1],
       [0, 1],
       [2, 3],
       [2, 3],
       [2, 3],
       [2, 3],
       [2, 3]])

In [117]:
a = np.arange(4).reshape(2, -1)
np.repeat(a, (2, 5), axis=1)

array([[0, 0, 1, 1, 1, 1, 1],
       [2, 2, 3, 3, 3, 3, 3]])

# Set operations

In [6]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

np.intersect1d(a, b), np.setdiff1d(a, b)

(array([2, 4]), array([1, 3, 5, 6]))

# Matching positions and elements

In [7]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

np.where(a == b), a[a==b]

((array([1, 3, 5, 7]),), array([2, 2, 4, 4]))

# Boolean indexing

In [8]:
a[a > 4]

array([5, 6])

# Swapping columns

In [9]:
a = np.arange(10).reshape(2, -1)
a[:, [1, 2, 3, 0, 4]]

array([[1, 2, 3, 0, 4],
       [6, 7, 8, 5, 9]])

# Standardizing and normalizing

Standardizing: mean 0, std 1

In [10]:
a = np.random.uniform(size=(5, 4), low=-5, high=10)
a

array([[ 9.60242896,  2.55365063, -2.7926332 ,  9.4338791 ],
       [ 6.32984843,  7.74590298,  2.32242242,  1.2092394 ],
       [-4.66673393,  2.52871619,  8.34083387,  7.55587159],
       [ 9.76738436,  0.84931679,  3.30697691,  5.32679511],
       [ 2.75009282, -4.82592717, -0.27825768,  2.1585147 ]])

In [11]:
(a - a.mean()) / a.std()

array([[ 1.39302295, -0.2057867 , -1.41843515,  1.35479233],
       [ 0.65073357,  0.97192421, -0.25823407, -0.51072715],
       [-1.84352021, -0.21144235,  1.10686692,  0.92882114],
       [ 1.43043827, -0.59236509, -0.03491661,  0.42322019],
       [-0.16122952, -1.87962855, -0.84812245, -0.29541175]])

Normalizing: squash into range [0, 1)

In [12]:
(a - a.min()) / a.ptp()

array([[0.98869651, 0.5056822 , 0.13933054, 0.9771467 ],
       [0.76444442, 0.86147891, 0.48983739, 0.41355703],
       [0.01090864, 0.50397357, 0.90224628, 0.8484571 ],
       [1.        , 0.3888935 , 0.55730353, 0.69571065],
       [0.51914331, 0.        , 0.31162697, 0.47860569]])

# `np.digitize`

In [17]:
a = np.arange(1, 11).reshape(2, -1)
np.digitize(a, bins=[1, 4, 8])

array([[1, 1, 1, 2, 2],
       [2, 2, 3, 3, 3]])

# Local peaks

In [42]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

diff1 = a - np.hstack((a[1:], 0))
diff2 = a - np.hstack((0, a[:-1]))
np.where((diff1>0) & (diff2>0))

(array([2, 5, 7]),)

In [52]:
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
b = np.array([1,2,3])

a - b[:, None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [5]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

np.where(x == 1)[0][4]

8

In [10]:
np.where(x == x.min())

(array([ 0,  2,  3,  7,  8, 10, 11]),)

# Date range

In [68]:
np.arange(np.datetime64("2018-01-02"), np.datetime64("2018-01-15"), 3)

array(['2018-01-02', '2018-01-05', '2018-01-08', '2018-01-11',
       '2018-01-14'], dtype='datetime64[D]')

# Strides

In [96]:
a = np.arange(15)
stride = 2
window = 4
np.array([a[i:i+window] for i in range(0, a.shape[0]-window+1, stride)])

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])