In [1]:
import torch
import numpy as np

torch.__version__

'0.4.1'

In [2]:
a = torch.arange(1000).view((20, 10, 5))
a.size()

torch.Size([20, 10, 5])

In [3]:
a[1, 2].size(), a[1, 2, 3].size()

(torch.Size([5]), torch.Size([]))

In [4]:
idx = torch.LongTensor([[0, 2, 3], [0, 2, 4]])
a[idx].size(), a[idx[0]].size()

(torch.Size([2, 3, 10, 5]), torch.Size([3, 10, 5]))

In [5]:
a[[0, 0], [0, 0], [0, 1]]

tensor([0, 1])

In [6]:
idx
a[0, 2, 3]

tensor(13)

In [7]:
a[idx[:, 0], idx[:, 1], idx[:, 2]]

tensor([13, 14])

In [8]:
A = np.arange(24).reshape((4, 3, 2))
A[[3, 0, 0, 1], [1, 2, 2, 0], [0, 0, 0, 0]].shape

(4,)

In [9]:
A = np.arange(12).reshape((4, 3))
print(A)
A[[2, 0], [0, 1]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([6, 1])

In [10]:
idx = torch.LongTensor([0, 2, 1])
a[idx].size()
a.size(), a.select(0, 2).size()

(torch.Size([20, 10, 5]), torch.Size([10, 5]))

In [11]:
a.index_select(0, idx).size()

torch.Size([3, 10, 5])

In [12]:
b = torch.tensor([[1, 2], [3, 4], [5, 6]]) + 10
idx2 = torch.LongTensor([[0, 1]])

torch.gather(b, 0, idx2)

tensor([[11, 14]])

In [13]:
import numpy as np

In [14]:
A = np.arange(10, 16).reshape(3, 2)
A[[1, 0], [1, 0]]

array([13, 10])

# Pytorch masking

Set unmasked elements to zero.

In [15]:
x = torch.arange(10, 50, dtype=torch.float).view(4, 10)
xlen = torch.LongTensor([4, 8, 1, 10])

m = torch.arange(x.size(1)).unsqueeze(0).expand(x.size())

mask = xlen.unsqueeze(1).expand(x.size()) <= m
x[mask] = float('-inf')

x

tensor([[10.0000, 11.0000, 12.0000, 13.0000,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf],
        [20.0000, 21.0000, 22.0000, 23.0000, 24.0000, 25.0000, 26.0000, 27.0000,
            -inf,    -inf],
        [30.0000,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf],
        [40.0000, 41.0000, 42.0000, 43.0000, 44.0000, 45.0000, 46.0000, 47.0000,
         48.0000, 49.0000]])

In [16]:
s = torch.nn.Softmax(dim=-1)
s(x)

tensor([[0.0321, 0.0871, 0.2369, 0.6439, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0006, 0.0016, 0.0043, 0.0116, 0.0315, 0.0856, 0.2326, 0.6323, 0.0000,
         0.0000],
        [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0001, 0.0002, 0.0006, 0.0016, 0.0043, 0.0116, 0.0315, 0.0856, 0.2326,
         0.6321]])

# Accuracy using masked elements

In [17]:
ground_truth = torch.LongTensor(4, 5).random_(0, 3)
ground_truth

tensor([[2, 0, 0, 0, 0],
        [0, 2, 0, 1, 2],
        [2, 0, 2, 2, 2],
        [0, 0, 1, 1, 0]])

In [18]:
prediction = torch.LongTensor(4, 5).random_(0, 3)
prediction

tensor([[0, 2, 2, 0, 0],
        [1, 2, 2, 1, 0],
        [2, 0, 2, 2, 2],
        [0, 1, 1, 0, 0]])

In [19]:
doc_lens = torch.LongTensor([2, 5, 4, 1])

In [20]:
m = torch.arange(ground_truth.size(1)).unsqueeze(0).expand(ground_truth.size())
mask = doc_lens.unsqueeze(1).expand(ground_truth.size()) <= m
mask

tensor([[0, 0, 1, 1, 1],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 1]], dtype=torch.uint8)

In [21]:
correct = torch.eq(ground_truth, prediction)
correct[mask] = 0
correct

tensor([[0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 0]], dtype=torch.uint8)

In [22]:
correct.sum().item() / doc_lens.sum().item()

0.5833333333333334